### ISSUE TITLE
Calendar event creation fails when timezone changes

### ISSUE THREAD

**Issue by RenneNiku** [kotope/ha_nordpool_cheapest_hours#13]
In the coming  night, we'll be adjusting our clocks once again. Advanced cheapest hours does not like that (though this is perhaps more problem with HA itself), The cheapest 5 hours would be from midnight to 05:00. But, due to the fact it is time to adjust our clocks, 00 and 05 are on different timezone:

```
    start_date_time: '2024-03-31T00:00:00+02:00'
    end_date_time: '2024-03-31T05:00:00+03:00'
    summary: Cheapest hours energy
    entity_id:
      - calendar.electricity
```

And calendar event creation fails:

`homeassistant  | 2024-03-30 15:00:00.436 ERROR (MainThread) [homeassistant.components.automation.cheapest_hours_set_next_cheapest_sequence] Error while executing automation automation.cheapest_hours_set_next_cheapest_sequence: Expected all values to have the same timezone
`

As `input_boolean.cheapest_hours_set`is already set,  I'd assume failsafe would not be tried. And even if it would, it has the same problem: Start time & end time are having different timezone.

As a result, there's not schedule for the coming night to turn on anything.

Perhaps failsafe should not use calendar?

This only happen twice a year, but if you don't remember it you got cold shower and lots of angry family members around you in the morning.
