### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by rinowit** [kotope/ha_nordpool_cheapest_hours#16]
Hello,
I am not new to Home Assistant. But im not sure what im doing wrong. But cant get it to work.

1)I have nordpool installed and it's working. I have changed the name of the sensor to: sensor.nordpool

2)I have installed the add on calendar with a calendar named "electricity"

3)I have copyed the .yaml files to my Home Assistant and made the package entry "cheapest_hours_non_sequential: !include advanced_cheapest_hours_non_sequential.yaml" in the configuration.yaml file. It work as I can see all the entities and automations appare.

I have changed alle the values I am supposed to change to point to the right nordpool sensor in the .yaml file. Only ting im unsure of is the time from/to. I have put in the value 0 and 23

My sensor "sensor.cheapest_hours_energy_non_sequential" only showes failsafe time. No other entries.

```
friendly_name: Cheapest hours energy (non-sequential)
number_of_hours: "10"
first_hour: "0"
last_hour: "23"
starting_today: "True"
sensor: sensor.nordpool
fail_safe_starting: "00:00"
list: []
failsafe:
  - start: "2024-10-30T00:00:00+01:00"
    end: "2024-10-30T10:00:00+01:00"
```

Thank for helping
