### ISSUE TITLE
Error message: Component input_datetime has duplicate key 'name'

### ISSUE THREAD

**Issue by ghost** [kotope/ha_nordpool_cheapest_hours#5]
Hello,

I'm interested in your solution to automate some of my instances at the lowest and the most expensive energy prices. I followed you installation guide by copying the two YAML-Files to my NUC running dedicated HA-OS.

I add the following lines in my configuration.yaml:

```
homeassistant:
  packages:
    nordpool_cheapest_hours: !include nordpool_cheapest_hours.yaml
    nordpool_most_expensive_hours: !include nordpool_cheapest_hours.yaml
```

When running the configuration.yaml check I get the following message:

![image](https://user-images.githubusercontent.com/99020676/223516431-7ddc2ab6-6e57-494d-9f26-822f9cf476ef.png)

When placing a # for one of the two nordpool_xxx lines there is no error.

Anny idea what here is going wrong.
